// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"fmt"

	"github.com/maxcalandrelli/gocc/example/mail/mail.grammar/mail/internal/token"
)

type ActionTable [NumStates]ActionRow

type ActionRow struct {
	Accept token.Type
	Ignore string
}

func (a ActionRow) String() string {
	return fmt.Sprintf("Accept=%d, Ignore=%s", a.Accept, a.Ignore)
}

var ActTab = ActionTable{
	ActionRow{ // S0, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S1, Ignore("!whitespace")
		Accept: -1,
		Ignore: "!whitespace",
	},
	ActionRow{ // S2, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S3, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S4, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S5, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S6, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S7, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S8, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S9, Accept("addrspec")
		Accept: 2,
		Ignore: "",
	},
	ActionRow{ // S10, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S11, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S12, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S13, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S14, Accept("addrspec")
		Accept: 2,
		Ignore: "",
	},
}
