// Code generated by gocc; DO NOT EDIT.

package mail

import (
	"io"

	"github.com/maxcalandrelli/gocc/example/mail/mail.grammar/mail/internal/lexer"
	"github.com/maxcalandrelli/gocc/example/mail/mail.grammar/mail/internal/token"
)

const (
	INVALID = token.INVALID
	EOF     = token.EOF
)

type (
	Token    = token.Token
	TokenMap = token.TokenMap
	Pos      = token.Pos
	Lexer    = lexer.Lexer
)

func NewLexerBytes(src []byte) *lexer.Lexer {
	return lexer.NewLexerBytes(src)
}

func NewLexerString(src string) *lexer.Lexer {
	return lexer.NewLexerBytes([]byte(src))
}

func NewLexerFile(fpath string) (*lexer.Lexer, error) {
	return lexer.NewLexerFile(fpath)
}

func NewLexer(reader io.Reader) (*lexer.Lexer, error) {
	return lexer.NewLexer(reader)
}

func GetTokenMap() TokenMap {
	return token.TokMap
}
