token : _token | _token _crlf ;

!ws : '\t' | '\n' | '\r' | ' ' ;

!comment: ';' {.} '\n' ;

/* Block Comment */

_crlf : '\r' '\n' ;

_token : _token1 | _token2 | _token3 ;

_token1 : 't' 'o' 'k' 'e' 'n' '1' ;

_token2 : 't' 'o' 'k' 'e' 'n' '2' ;

// Line comment

_token3 : 't' 'o' 'k' 'e' 'n' '3' ;

