// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 2

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // Π<S'>
		1, // Π<Stmt>
	},
	gotoRow{ // S1
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S2
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S3
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S4
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S5
		-1, // Π<S'>
		6, // Π<Stmt>
	},
	gotoRow{ // S6
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S7
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S8
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S9
		-1, // Π<S'>
		11, // Π<Stmt>
	},
	gotoRow{ // S10
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S11
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S12
		-1, // Π<S'>
		13, // Π<Stmt>
	},
	gotoRow{ // S13
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
	gotoRow{ // S14
		-1, // Π<S'>
		15, // Π<Stmt>
	},
	gotoRow{ // S15
		-1, // Π<S'>
		-1, // Π<Stmt>
	},
}
