regenerate:
	(cd astx && make regenerate)
	(cd bools && make regenerate)
	(cd calc && make regenerate)
	(cd errorrecovery && make regenerate)
	(cd mail && make regenerate)
	(cd nolexer && make regenerate)
	(cd rr && make regenerate)
	(cd sr && make regenerate)
