// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(3), // ...42..., reduce: ImportList
			nil,       // empty
			shift(5),  // import
			nil,       // identifier
			nil,       // ;
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // ...42...
			nil,          // empty
			nil,          // import
			nil,          // identifier
			nil,          // ;
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(6), // ...42...
			nil,      // empty
			nil,      // import
			nil,      // identifier
			nil,      // ;
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(2), // ...42..., reduce: ImportList
			nil,       // empty
			shift(5),  // import
			nil,       // identifier
			nil,       // ;
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(4), // ...42..., reduce: Imports
			nil,       // empty
			reduce(4), // import, reduce: Imports
			nil,       // identifier
			nil,       // ;
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // ...42...
			nil,      // empty
			nil,      // import
			shift(8), // identifier
			nil,      // ;
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: File
			nil,       // ...42...
			nil,       // empty
			nil,       // import
			nil,       // identifier
			nil,       // ;
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(5), // ...42..., reduce: Imports
			nil,       // empty
			reduce(5), // import, reduce: Imports
			nil,       // identifier
			nil,       // ;
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // ...42...
			nil,      // empty
			nil,      // import
			nil,      // identifier
			shift(9), // ;
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // ...42..., reduce: Import
			nil,       // empty
			reduce(6), // import, reduce: Import
			nil,       // identifier
			nil,       // ;
		},
	},
}
