// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // File
		2,  // ImportList
		3,  // Imports
		4,  // Import
	},
	gotoRow{ // S1
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
	gotoRow{ // S2
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
	gotoRow{ // S3
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		7,  // Import
	},
	gotoRow{ // S4
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
	gotoRow{ // S5
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
	gotoRow{ // S6
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
	gotoRow{ // S7
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
	gotoRow{ // S8
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
	gotoRow{ // S9
		-1, // S'
		-1, // File
		-1, // ImportList
		-1, // Imports
		-1, // Import
	},
}
