// Code generated by gocc; DO NOT EDIT.

package parser

import "github.com/goccmack/gocc/example/usercontext/ast"

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : File	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `File : ImportList "...42..."	<<  >>`,
		Id:         "File",
		NTType:     1,
		Index:      1,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ImportList : Imports	<<  >>`,
		Id:         "ImportList",
		NTType:     2,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ImportList : empty	<<  >>`,
		Id:         "ImportList",
		NTType:     2,
		Index:      3,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Imports : Import	<< ast.NewImportList(X[0]) >>`,
		Id:         "Imports",
		NTType:     3,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewImportList(X[0])
		},
	},
	ProdTabEntry{
		String: `Imports : Imports Import	<< ast.AppendImportToList(X[0], X[1]) >>`,
		Id:         "Imports",
		NTType:     3,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendImportToList(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Import : "import" identifier ";"	<< ast.NewImport(X[1], C) >>`,
		Id:         "Import",
		NTType:     4,
		Index:      6,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewImport(X[1], C)
		},
	},
}
