run:
  timeout: 60s
linters:
  enable:
    - dogsled
    - dupl
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - prealloc
    - unconvert
    - whitespace
  disable:
    - unused
    - depguard
    - govet
    - staticcheck
    - typecheck
