// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
	"strconv"
	"unicode/utf8"
)

type Token struct {
	Type
	Lit           []byte
	IgnoredPrefix []byte
	Pos
	ForeignAstNode interface{}
	Foreign        bool
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

func (p Pos) StartingFrom(base Pos) Pos {
	r := base
	r.Offset += p.Offset
	r.Line += p.Line
	r.Column = p.Column
	if p.Line > 0 && base.Line > 0 {
		r.Line--
	}
	if r.Column < 1 {
		r.Column = 1
	}
	return r
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
	litMap  map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	return fmt.Sprintf("%s(%d,<%s>)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

// CharLiteralValue returns the string value of the char literal.
func (t *Token) CharLiteralValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

// Float32Value returns the float32 value of the token or an error if the token literal does not
// denote a valid float32.
func (t *Token) Float32Value() (float32, error) {
	if v, err := strconv.ParseFloat(string(t.Lit), 32); err != nil {
		return 0, err
	} else {
		return float32(v), nil
	}
}

// Float64Value returns the float64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Float64Value() (float64, error) {
	return strconv.ParseFloat(string(t.Lit), 64)
}

// IDValue returns the string representation of an identifier token.
func (t *Token) IDValue() string {
	return string(t.Lit)
}

// Int32Value returns the int32 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int32Value() (int32, error) {
	if v, err := strconv.ParseInt(string(t.Lit), 10, 64); err != nil {
		return 0, err
	} else {
		return int32(v), nil
	}
}

// Int64Value returns the int64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int64Value() (int64, error) {
	return strconv.ParseInt(string(t.Lit), 10, 64)
}

// UTF8Rune decodes the UTF8 rune in the token literal. It returns utf8.RuneError if
// the token literal contains an invalid rune.
func (t *Token) UTF8Rune() (rune, error) {
	r, _ := utf8.DecodeRune(t.Lit)
	if r == utf8.RuneError {
		err := fmt.Errorf("Invalid rune")
		return r, err
	}
	return r, nil
}

// StringValue returns the string value of the token literal.
func (t *Token) StringValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"Ω",
		"tokId",
		"Λ<:>",
		"Λ<;>",
		"regDefId",
		"ignoredTokId",
		"Λ<|>",
		"Λ<.>",
		"char_lit",
		"Λ<->",
		"Λ<~>",
		"Λ<(>",
		"Λ<)>",
		"Λ<[>",
		"Λ<]>",
		"Λ<{>",
		"Λ<}>",
		"g_sdt_lit",
		"prodId",
		"string_lit",
		"g_ctxdep_lit",
		"Λ<@>",
		"Λ<error>",
		"Λ<λ>",
		"Λ<empty>",
		"Λ<ε>",
	},

	idMap: map[string]Type{
		"INVALID":      0,
		"Ω":            1,
		"tokId":        2,
		"Λ<:>":         3,
		"Λ<;>":         4,
		"regDefId":     5,
		"ignoredTokId": 6,
		"Λ<|>":         7,
		"Λ<.>":         8,
		"char_lit":     9,
		"Λ<->":         10,
		"Λ<~>":         11,
		"Λ<(>":         12,
		"Λ<)>":         13,
		"Λ<[>":         14,
		"Λ<]>":         15,
		"Λ<{>":         16,
		"Λ<}>":         17,
		"g_sdt_lit":    18,
		"prodId":       19,
		"string_lit":   20,
		"g_ctxdep_lit": 21,
		"Λ<@>":         22,
		"Λ<error>":     23,
		"Λ<λ>":         24,
		"Λ<empty>":     25,
		"Λ<ε>":         26,
	},

	litMap: map[string]Type{
		":":     3,
		";":     4,
		"|":     7,
		".":     8,
		"-":     10,
		"~":     11,
		"(":     12,
		")":     13,
		"[":     14,
		"]":     15,
		"{":     16,
		"}":     17,
		"@":     22,
		"error": 23,
		"λ":     24,
		"empty": 25,
		"ε":     26,
	},
}
