// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 6

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // Π<S'>
		1, // Π<BoolExpr>
		2, // Π<BoolExpr1>
		3, // Π<Val>
		4, // Π<CompareExpr>
		5, // Π<SubStringExpr>
	},
	gotoRow{ // S1
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S2
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S3
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S4
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S5
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S6
		-1, // Π<S'>
		13, // Π<BoolExpr>
		14, // Π<BoolExpr1>
		15, // Π<Val>
		16, // Π<CompareExpr>
		17, // Π<SubStringExpr>
	},
	gotoRow{ // S7
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S8
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S9
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S10
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S11
		-1, // Π<S'>
		26, // Π<BoolExpr>
		27, // Π<BoolExpr1>
		3, // Π<Val>
		4, // Π<CompareExpr>
		5, // Π<SubStringExpr>
	},
	gotoRow{ // S12
		-1, // Π<S'>
		26, // Π<BoolExpr>
		28, // Π<BoolExpr1>
		3, // Π<Val>
		4, // Π<CompareExpr>
		5, // Π<SubStringExpr>
	},
	gotoRow{ // S13
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S14
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S15
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S16
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S17
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S18
		-1, // Π<S'>
		32, // Π<BoolExpr>
		14, // Π<BoolExpr1>
		15, // Π<Val>
		16, // Π<CompareExpr>
		17, // Π<SubStringExpr>
	},
	gotoRow{ // S19
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S20
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S21
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S22
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S23
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S24
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S25
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S26
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S27
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S28
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S29
		-1, // Π<S'>
		39, // Π<BoolExpr>
		40, // Π<BoolExpr1>
		15, // Π<Val>
		16, // Π<CompareExpr>
		17, // Π<SubStringExpr>
	},
	gotoRow{ // S30
		-1, // Π<S'>
		39, // Π<BoolExpr>
		41, // Π<BoolExpr1>
		15, // Π<Val>
		16, // Π<CompareExpr>
		17, // Π<SubStringExpr>
	},
	gotoRow{ // S31
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S32
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S33
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S34
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S35
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S36
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S37
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S38
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S39
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S40
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S41
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S42
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S43
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S44
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
	gotoRow{ // S45
		-1, // Π<S'>
		-1, // Π<BoolExpr>
		-1, // Π<BoolExpr1>
		-1, // Π<Val>
		-1, // Π<CompareExpr>
		-1, // Π<SubStringExpr>
	},
}
