// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 59: // [';',';']
			return 2
		case r == 61: // ['=','=']
			return 3
		case r == 100: // ['d','d']
			return 4
		case r == 108: // ['l','l']
			return 5
		case r == 945: // [\u03b1,\u03b1]
			return 6
		case r == 946: // [\u03b2,\u03b2]
			return 7
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 8
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 9
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 945: // [\u03b1,\u03b1]
			return 10
		case r == 946: // [\u03b2,\u03b2]
			return 11
		case r == 947: // [\u03b3,\u03b3]
			return 12
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 13
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 102: // ['f','f']
			return 14
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 116: // ['t','t']
			return 15
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 945: // [\u03b1,\u03b1]
			return 10
		case r == 946: // [\u03b2,\u03b2]
			return 11
		case r == 947: // [\u03b3,\u03b3]
			return 12
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 945: // [\u03b1,\u03b1]
			return 10
		case r == 946: // [\u03b2,\u03b2]
			return 11
		case r == 947: // [\u03b3,\u03b3]
			return 12
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 13
		case r == 945: // [\u03b1,\u03b1]
			return 17
		case r == 946: // [\u03b2,\u03b2]
			return 18
		case r == 947: // [\u03b3,\u03b3]
			return 12
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 105: // ['i','i']
			return 19
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		case r == 945: // [\u03b1,\u03b1]
			return 10
		case r == 946: // [\u03b2,\u03b2]
			return 11
		case r == 947: // [\u03b3,\u03b3]
			return 12
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 945: // [\u03b1,\u03b1]
			return 10
		case r == 946: // [\u03b2,\u03b2]
			return 11
		case r == 947: // [\u03b3,\u03b3]
			return 12
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 20
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 21
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 20
		case r == 945: // [\u03b1,\u03b1]
			return 17
		case r == 946: // [\u03b2,\u03b2]
			return 18
		case r == 947: // [\u03b3,\u03b3]
			return 12
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 22
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
