// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"fmt"

	"github.com/maxcalandrelli/gocc/example/calc/calc.grammar/calc/internal/token"
)

type ActionTable [NumStates]ActionRow

type ActionRow struct {
	Accept token.Type
	Ignore string
}

func (a ActionRow) String() string {
	return fmt.Sprintf("Accept=%d, Ignore=%s", a.Accept, a.Ignore)
}

var ActTab = ActionTable{
	ActionRow{ // S0, 
		Accept: 0,
		Ignore: "",
	},
	ActionRow{ // S1, Ignore("!whitespace")
		Accept: -1,
		Ignore: "!whitespace",
	},
	ActionRow{ // S2, Accept("Λ<(>")
		Accept: 6,
		Ignore: "",
	},
	ActionRow{ // S3, Accept("Λ<)>")
		Accept: 7,
		Ignore: "",
	},
	ActionRow{ // S4, Accept("Λ<*>")
		Accept: 4,
		Ignore: "",
	},
	ActionRow{ // S5, Accept("Λ<+>")
		Accept: 2,
		Ignore: "",
	},
	ActionRow{ // S6, Accept("Λ<->")
		Accept: 3,
		Ignore: "",
	},
	ActionRow{ // S7, Accept("Λ</>")
		Accept: 5,
		Ignore: "",
	},
	ActionRow{ // S8, Accept("int64")
		Accept: 8,
		Ignore: "",
	},
	ActionRow{ // S9, Accept("int64")
		Accept: 8,
		Ignore: "",
	},
}
