// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(6),  // tokId
			nil,       // :
			nil,       // ;
			shift(7),  // regDefId
			shift(8),  // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			shift(11), // g_sdt_lit
			shift(13), // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // tokId
			nil,          // :
			nil,          // ;
			nil,          // regDefId
			nil,          // ignoredTokId
			nil,          // |
			nil,          // .
			nil,          // char_lit
			nil,          // ~
			nil,          // -
			nil,          // (
			nil,          // )
			nil,          // [
			nil,          // ]
			nil,          // {
			nil,          // }
			nil,          // g_sdt_lit
			nil,          // prodId
			nil,          // error
			nil,          // empty
			nil,          // string_lit
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Grammar
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			shift(11), // g_sdt_lit
			shift(13), // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Grammar
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: LexicalPart
			shift(6),  // tokId
			nil,       // :
			nil,       // ;
			shift(7),  // regDefId
			shift(8),  // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			reduce(4), // g_sdt_lit, reduce: LexicalPart
			reduce(4), // prodId, reduce: LexicalPart
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: LexProductions
			reduce(5), // tokId, reduce: LexProductions
			nil,       // :
			nil,       // ;
			reduce(5), // regDefId, reduce: LexProductions
			reduce(5), // ignoredTokId, reduce: LexProductions
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			reduce(5), // g_sdt_lit, reduce: LexProductions
			reduce(5), // prodId, reduce: LexProductions
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			shift(16), // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			shift(17), // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			shift(18), // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			shift(13), // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(24), // $, reduce: SyntaxPart
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			shift(13),  // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			reduce(25), // prodId, reduce: FileHeader
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(26), // $, reduce: SyntaxProdList
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			reduce(26), // prodId, reduce: SyntaxProdList
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			shift(21), // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Grammar
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: LexProductions
			reduce(6), // tokId, reduce: LexProductions
			nil,       // :
			nil,       // ;
			reduce(6), // regDefId, reduce: LexProductions
			reduce(6), // ignoredTokId, reduce: LexProductions
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			reduce(6), // g_sdt_lit, reduce: LexProductions
			reduce(6), // prodId, reduce: LexProductions
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(23), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			shift(28), // ~
			nil,       // -
			shift(29), // (
			nil,       // )
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(23), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			shift(28), // ~
			nil,       // -
			shift(29), // (
			nil,       // )
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(23), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			shift(28), // ~
			nil,       // -
			shift(29), // (
			nil,       // )
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(23), // $, reduce: SyntaxPart
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			shift(13),  // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(27), // $, reduce: SyntaxProdList
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			reduce(27), // prodId, reduce: SyntaxProdList
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S21
		canRecover: true,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			shift(34),  // tokId
			nil,        // :
			reduce(36), // ;, reduce: SyntaxBody
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(36), // |, reduce: SyntaxBody
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			shift(35),  // prodId
			shift(39),  // error
			nil,        // empty
			shift(41),  // string_lit
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			shift(42), // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			shift(43), // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(19), // ;, reduce: LexTerm
			reduce(19), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(19), // |, reduce: LexTerm
			reduce(19), // ., reduce: LexTerm
			reduce(19), // char_lit, reduce: LexTerm
			reduce(19), // ~, reduce: LexTerm
			nil,        // -
			reduce(19), // (, reduce: LexTerm
			nil,        // )
			reduce(19), // [, reduce: LexTerm
			nil,        // ]
			reduce(19), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(10), // ;, reduce: LexPattern
			shift(23),  // regDefId
			nil,        // ignoredTokId
			reduce(10), // |, reduce: LexPattern
			shift(26),  // .
			shift(27),  // char_lit
			shift(28),  // ~
			nil,        // -
			shift(29),  // (
			nil,        // )
			shift(30),  // [
			nil,        // ]
			shift(31),  // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(12), // ;, reduce: LexAlt
			reduce(12), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(12), // |, reduce: LexAlt
			reduce(12), // ., reduce: LexAlt
			reduce(12), // char_lit, reduce: LexAlt
			reduce(12), // ~, reduce: LexAlt
			nil,        // -
			reduce(12), // (, reduce: LexAlt
			nil,        // )
			reduce(12), // [, reduce: LexAlt
			nil,        // ]
			reduce(12), // {, reduce: LexAlt
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(14), // ;, reduce: LexTerm
			reduce(14), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // ~, reduce: LexTerm
			nil,        // -
			reduce(14), // (, reduce: LexTerm
			nil,        // )
			reduce(14), // [, reduce: LexTerm
			nil,        // ]
			reduce(14), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(15), // ;, reduce: LexTerm
			reduce(15), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // ~, reduce: LexTerm
			shift(45),  // -
			reduce(15), // (, reduce: LexTerm
			nil,        // )
			reduce(15), // [, reduce: LexTerm
			nil,        // ]
			reduce(15), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			shift(46), // char_lit
			nil,       // ~
			nil,       // -
			shift(47), // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(49), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(52), // .
			shift(53), // char_lit
			shift(54), // ~
			nil,       // -
			shift(55), // (
			nil,       // )
			shift(56), // [
			nil,       // ]
			shift(57), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(59), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(62), // .
			shift(63), // char_lit
			shift(64), // ~
			nil,       // -
			shift(65), // (
			nil,       // )
			shift(66), // [
			nil,       // ]
			shift(67), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(69), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(72), // .
			shift(73), // char_lit
			shift(74), // ~
			nil,       // -
			shift(75), // (
			nil,       // )
			shift(76), // [
			nil,       // ]
			shift(77), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			shift(78), // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			shift(43), // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			shift(79), // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			shift(43), // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(40), // tokId, reduce: Symbol
			nil,        // :
			reduce(40), // ;, reduce: Symbol
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(40), // |, reduce: Symbol
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			reduce(40), // g_sdt_lit, reduce: Symbol
			reduce(40), // prodId, reduce: Symbol
			nil,        // error
			nil,        // empty
			reduce(40), // string_lit, reduce: Symbol
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(39), // tokId, reduce: Symbol
			nil,        // :
			reduce(39), // ;, reduce: Symbol
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(39), // |, reduce: Symbol
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			reduce(39), // g_sdt_lit, reduce: Symbol
			reduce(39), // prodId, reduce: Symbol
			nil,        // error
			nil,        // empty
			reduce(39), // string_lit, reduce: Symbol
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			shift(80), // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			shift(81), // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(29), // ;, reduce: Alternatives
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(29), // |, reduce: Alternatives
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			shift(34),  // tokId
			nil,        // :
			reduce(31), // ;, reduce: SyntaxBody
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(31), // |, reduce: SyntaxBody
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			shift(82),  // g_sdt_lit
			shift(35),  // prodId
			nil,        // error
			nil,        // empty
			shift(41),  // string_lit
		},
	},
	actionRow{ // S39
		canRecover: true,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			shift(34),  // tokId
			nil,        // :
			reduce(33), // ;, reduce: SyntaxBody
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(33), // |, reduce: SyntaxBody
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			shift(35),  // prodId
			nil,        // error
			nil,        // empty
			shift(41),  // string_lit
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(37), // tokId, reduce: Symbols
			nil,        // :
			reduce(37), // ;, reduce: Symbols
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(37), // |, reduce: Symbols
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			reduce(37), // g_sdt_lit, reduce: Symbols
			reduce(37), // prodId, reduce: Symbols
			nil,        // error
			nil,        // empty
			reduce(37), // string_lit, reduce: Symbols
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(41), // tokId, reduce: Symbol
			nil,        // :
			reduce(41), // ;, reduce: Symbol
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(41), // |, reduce: Symbol
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			reduce(41), // g_sdt_lit, reduce: Symbol
			reduce(41), // prodId, reduce: Symbol
			nil,        // error
			nil,        // empty
			reduce(41), // string_lit, reduce: Symbol
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // $, reduce: LexProduction
			reduce(7), // tokId, reduce: LexProduction
			nil,       // :
			nil,       // ;
			reduce(7), // regDefId, reduce: LexProduction
			reduce(7), // ignoredTokId, reduce: LexProduction
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			reduce(7), // g_sdt_lit, reduce: LexProduction
			reduce(7), // prodId, reduce: LexProduction
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(23), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			shift(28), // ~
			nil,       // -
			shift(29), // (
			nil,       // )
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(13), // ;, reduce: LexAlt
			reduce(13), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(13), // |, reduce: LexAlt
			reduce(13), // ., reduce: LexAlt
			reduce(13), // char_lit, reduce: LexAlt
			reduce(13), // ~, reduce: LexAlt
			nil,        // -
			reduce(13), // (, reduce: LexAlt
			nil,        // )
			reduce(13), // [, reduce: LexAlt
			nil,        // ]
			reduce(13), // {, reduce: LexAlt
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			shift(86), // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(16), // ;, reduce: LexTerm
			reduce(16), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // ~, reduce: LexTerm
			nil,        // -
			reduce(16), // (, reduce: LexTerm
			nil,        // )
			reduce(16), // [, reduce: LexTerm
			nil,        // ]
			reduce(16), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			shift(87), // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			shift(88), // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			shift(89), // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(19), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(19), // |, reduce: LexTerm
			reduce(19), // ., reduce: LexTerm
			reduce(19), // char_lit, reduce: LexTerm
			reduce(19), // ~, reduce: LexTerm
			nil,        // -
			reduce(19), // (, reduce: LexTerm
			reduce(19), // ), reduce: LexTerm
			reduce(19), // [, reduce: LexTerm
			nil,        // ]
			reduce(19), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			shift(49),  // regDefId
			nil,        // ignoredTokId
			reduce(10), // |, reduce: LexPattern
			shift(52),  // .
			shift(53),  // char_lit
			shift(54),  // ~
			nil,        // -
			shift(55),  // (
			reduce(10), // ), reduce: LexPattern
			shift(56),  // [
			nil,        // ]
			shift(57),  // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(12), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(12), // |, reduce: LexAlt
			reduce(12), // ., reduce: LexAlt
			reduce(12), // char_lit, reduce: LexAlt
			reduce(12), // ~, reduce: LexAlt
			nil,        // -
			reduce(12), // (, reduce: LexAlt
			reduce(12), // ), reduce: LexAlt
			reduce(12), // [, reduce: LexAlt
			nil,        // ]
			reduce(12), // {, reduce: LexAlt
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(14), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // ~, reduce: LexTerm
			nil,        // -
			reduce(14), // (, reduce: LexTerm
			reduce(14), // ), reduce: LexTerm
			reduce(14), // [, reduce: LexTerm
			nil,        // ]
			reduce(14), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(15), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // ~, reduce: LexTerm
			shift(91),  // -
			reduce(15), // (, reduce: LexTerm
			reduce(15), // ), reduce: LexTerm
			reduce(15), // [, reduce: LexTerm
			nil,        // ]
			reduce(15), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			nil,       // |
			nil,       // .
			shift(92), // char_lit
			nil,       // ~
			nil,       // -
			shift(93), // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(49), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(52), // .
			shift(53), // char_lit
			shift(54), // ~
			nil,       // -
			shift(55), // (
			nil,       // )
			shift(56), // [
			nil,       // ]
			shift(57), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(59), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(62), // .
			shift(63), // char_lit
			shift(64), // ~
			nil,       // -
			shift(65), // (
			nil,       // )
			shift(66), // [
			nil,       // ]
			shift(67), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(69), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(72), // .
			shift(73), // char_lit
			shift(74), // ~
			nil,       // -
			shift(75), // (
			nil,       // )
			shift(76), // [
			nil,       // ]
			shift(77), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			nil,       // regDefId
			nil,       // ignoredTokId
			shift(97), // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			shift(98), // ]
			nil,       // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(19), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(19), // |, reduce: LexTerm
			reduce(19), // ., reduce: LexTerm
			reduce(19), // char_lit, reduce: LexTerm
			reduce(19), // ~, reduce: LexTerm
			nil,        // -
			reduce(19), // (, reduce: LexTerm
			nil,        // )
			reduce(19), // [, reduce: LexTerm
			reduce(19), // ], reduce: LexTerm
			reduce(19), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			shift(59),  // regDefId
			nil,        // ignoredTokId
			reduce(10), // |, reduce: LexPattern
			shift(62),  // .
			shift(63),  // char_lit
			shift(64),  // ~
			nil,        // -
			shift(65),  // (
			nil,        // )
			shift(66),  // [
			reduce(10), // ], reduce: LexPattern
			shift(67),  // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(12), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(12), // |, reduce: LexAlt
			reduce(12), // ., reduce: LexAlt
			reduce(12), // char_lit, reduce: LexAlt
			reduce(12), // ~, reduce: LexAlt
			nil,        // -
			reduce(12), // (, reduce: LexAlt
			nil,        // )
			reduce(12), // [, reduce: LexAlt
			reduce(12), // ], reduce: LexAlt
			reduce(12), // {, reduce: LexAlt
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(14), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // ~, reduce: LexTerm
			nil,        // -
			reduce(14), // (, reduce: LexTerm
			nil,        // )
			reduce(14), // [, reduce: LexTerm
			reduce(14), // ], reduce: LexTerm
			reduce(14), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(15), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // ~, reduce: LexTerm
			shift(100), // -
			reduce(15), // (, reduce: LexTerm
			nil,        // )
			reduce(15), // [, reduce: LexTerm
			reduce(15), // ], reduce: LexTerm
			reduce(15), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(101), // char_lit
			nil,        // ~
			nil,        // -
			shift(102), // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(49), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(52), // .
			shift(53), // char_lit
			shift(54), // ~
			nil,       // -
			shift(55), // (
			nil,       // )
			shift(56), // [
			nil,       // ]
			shift(57), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(59), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(62), // .
			shift(63), // char_lit
			shift(64), // ~
			nil,       // -
			shift(65), // (
			nil,       // )
			shift(66), // [
			nil,       // ]
			shift(67), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(69), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(72), // .
			shift(73), // char_lit
			shift(74), // ~
			nil,       // -
			shift(75), // (
			nil,       // )
			shift(76), // [
			nil,       // ]
			shift(77), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(106), // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			shift(107), // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(19), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(19), // |, reduce: LexTerm
			reduce(19), // ., reduce: LexTerm
			reduce(19), // char_lit, reduce: LexTerm
			reduce(19), // ~, reduce: LexTerm
			nil,        // -
			reduce(19), // (, reduce: LexTerm
			nil,        // )
			reduce(19), // [, reduce: LexTerm
			nil,        // ]
			reduce(19), // {, reduce: LexTerm
			reduce(19), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			shift(69),  // regDefId
			nil,        // ignoredTokId
			reduce(10), // |, reduce: LexPattern
			shift(72),  // .
			shift(73),  // char_lit
			shift(74),  // ~
			nil,        // -
			shift(75),  // (
			nil,        // )
			shift(76),  // [
			nil,        // ]
			shift(77),  // {
			reduce(10), // }, reduce: LexPattern
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(12), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(12), // |, reduce: LexAlt
			reduce(12), // ., reduce: LexAlt
			reduce(12), // char_lit, reduce: LexAlt
			reduce(12), // ~, reduce: LexAlt
			nil,        // -
			reduce(12), // (, reduce: LexAlt
			nil,        // )
			reduce(12), // [, reduce: LexAlt
			nil,        // ]
			reduce(12), // {, reduce: LexAlt
			reduce(12), // }, reduce: LexAlt
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(14), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // ~, reduce: LexTerm
			nil,        // -
			reduce(14), // (, reduce: LexTerm
			nil,        // )
			reduce(14), // [, reduce: LexTerm
			nil,        // ]
			reduce(14), // {, reduce: LexTerm
			reduce(14), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(15), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // ~, reduce: LexTerm
			shift(109), // -
			reduce(15), // (, reduce: LexTerm
			nil,        // )
			reduce(15), // [, reduce: LexTerm
			nil,        // ]
			reduce(15), // {, reduce: LexTerm
			reduce(15), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(110), // char_lit
			nil,        // ~
			nil,        // -
			shift(111), // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(49), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(52), // .
			shift(53), // char_lit
			shift(54), // ~
			nil,       // -
			shift(55), // (
			nil,       // )
			shift(56), // [
			nil,       // ]
			shift(57), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(59), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(62), // .
			shift(63), // char_lit
			shift(64), // ~
			nil,       // -
			shift(65), // (
			nil,       // )
			shift(66), // [
			nil,       // ]
			shift(67), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(69), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(72), // .
			shift(73), // char_lit
			shift(74), // ~
			nil,       // -
			shift(75), // (
			nil,       // )
			shift(76), // [
			nil,       // ]
			shift(77), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // $, reduce: LexProduction
			reduce(8), // tokId, reduce: LexProduction
			nil,       // :
			nil,       // ;
			reduce(8), // regDefId, reduce: LexProduction
			reduce(8), // ignoredTokId, reduce: LexProduction
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			reduce(8), // g_sdt_lit, reduce: LexProduction
			reduce(8), // prodId, reduce: LexProduction
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // $, reduce: LexProduction
			reduce(9), // tokId, reduce: LexProduction
			nil,       // :
			nil,       // ;
			reduce(9), // regDefId, reduce: LexProduction
			reduce(9), // ignoredTokId, reduce: LexProduction
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // ~
			nil,       // -
			nil,       // (
			nil,       // )
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			reduce(9), // g_sdt_lit, reduce: LexProduction
			reduce(9), // prodId, reduce: LexProduction
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(28), // $, reduce: SyntaxProduction
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			reduce(28), // prodId, reduce: SyntaxProduction
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S81
		canRecover: true,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			shift(34),  // tokId
			nil,        // :
			reduce(36), // ;, reduce: SyntaxBody
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(36), // |, reduce: SyntaxBody
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			shift(35),  // prodId
			shift(39),  // error
			nil,        // empty
			shift(41),  // string_lit
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(32), // ;, reduce: SyntaxBody
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(32), // |, reduce: SyntaxBody
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(38), // tokId, reduce: Symbols
			nil,        // :
			reduce(38), // ;, reduce: Symbols
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(38), // |, reduce: Symbols
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			reduce(38), // g_sdt_lit, reduce: Symbols
			reduce(38), // prodId, reduce: Symbols
			nil,        // error
			nil,        // empty
			reduce(38), // string_lit, reduce: Symbols
		},
	},
	actionRow{ // S84
		canRecover: true,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			shift(34),  // tokId
			nil,        // :
			reduce(34), // ;, reduce: SyntaxBody
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(34), // |, reduce: SyntaxBody
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			shift(116), // g_sdt_lit
			shift(35),  // prodId
			nil,        // error
			nil,        // empty
			shift(41),  // string_lit
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(11), // ;, reduce: LexPattern
			shift(23),  // regDefId
			nil,        // ignoredTokId
			reduce(11), // |, reduce: LexPattern
			shift(26),  // .
			shift(27),  // char_lit
			shift(28),  // ~
			nil,        // -
			shift(29),  // (
			nil,        // )
			shift(30),  // [
			nil,        // ]
			shift(31),  // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(17), // ;, reduce: LexTerm
			reduce(17), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // ~, reduce: LexTerm
			nil,        // -
			reduce(17), // (, reduce: LexTerm
			nil,        // )
			reduce(17), // [, reduce: LexTerm
			nil,        // ]
			reduce(17), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			shift(117), // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(49), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(52), // .
			shift(53), // char_lit
			shift(54), // ~
			nil,       // -
			shift(55), // (
			nil,       // )
			shift(56), // [
			nil,       // ]
			shift(57), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(22), // ;, reduce: LexTerm
			reduce(22), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(22), // |, reduce: LexTerm
			reduce(22), // ., reduce: LexTerm
			reduce(22), // char_lit, reduce: LexTerm
			reduce(22), // ~, reduce: LexTerm
			nil,        // -
			reduce(22), // (, reduce: LexTerm
			nil,        // )
			reduce(22), // [, reduce: LexTerm
			nil,        // ]
			reduce(22), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(13), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(13), // |, reduce: LexAlt
			reduce(13), // ., reduce: LexAlt
			reduce(13), // char_lit, reduce: LexAlt
			reduce(13), // ~, reduce: LexAlt
			nil,        // -
			reduce(13), // (, reduce: LexAlt
			reduce(13), // ), reduce: LexAlt
			reduce(13), // [, reduce: LexAlt
			nil,        // ]
			reduce(13), // {, reduce: LexAlt
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(119), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(16), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // ~, reduce: LexTerm
			nil,        // -
			reduce(16), // (, reduce: LexTerm
			reduce(16), // ), reduce: LexTerm
			reduce(16), // [, reduce: LexTerm
			nil,        // ]
			reduce(16), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(120), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(88),  // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			shift(121), // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(97),  // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			shift(122), // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(106), // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			shift(123), // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(59), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(62), // .
			shift(63), // char_lit
			shift(64), // ~
			nil,       // -
			shift(65), // (
			nil,       // )
			shift(66), // [
			nil,       // ]
			shift(67), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(20), // ;, reduce: LexTerm
			reduce(20), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(20), // |, reduce: LexTerm
			reduce(20), // ., reduce: LexTerm
			reduce(20), // char_lit, reduce: LexTerm
			reduce(20), // ~, reduce: LexTerm
			nil,        // -
			reduce(20), // (, reduce: LexTerm
			nil,        // )
			reduce(20), // [, reduce: LexTerm
			nil,        // ]
			reduce(20), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(13), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(13), // |, reduce: LexAlt
			reduce(13), // ., reduce: LexAlt
			reduce(13), // char_lit, reduce: LexAlt
			reduce(13), // ~, reduce: LexAlt
			nil,        // -
			reduce(13), // (, reduce: LexAlt
			nil,        // )
			reduce(13), // [, reduce: LexAlt
			reduce(13), // ], reduce: LexAlt
			reduce(13), // {, reduce: LexAlt
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(125), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(16), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // ~, reduce: LexTerm
			nil,        // -
			reduce(16), // (, reduce: LexTerm
			nil,        // )
			reduce(16), // [, reduce: LexTerm
			reduce(16), // ], reduce: LexTerm
			reduce(16), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(126), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(88),  // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			shift(127), // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(97),  // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			shift(128), // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(106), // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			shift(129), // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S106
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // tokId
			nil,       // :
			nil,       // ;
			shift(69), // regDefId
			nil,       // ignoredTokId
			nil,       // |
			shift(72), // .
			shift(73), // char_lit
			shift(74), // ~
			nil,       // -
			shift(75), // (
			nil,       // )
			shift(76), // [
			nil,       // ]
			shift(77), // {
			nil,       // }
			nil,       // g_sdt_lit
			nil,       // prodId
			nil,       // error
			nil,       // empty
			nil,       // string_lit
		},
	},
	actionRow{ // S107
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(21), // ;, reduce: LexTerm
			reduce(21), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(21), // |, reduce: LexTerm
			reduce(21), // ., reduce: LexTerm
			reduce(21), // char_lit, reduce: LexTerm
			reduce(21), // ~, reduce: LexTerm
			nil,        // -
			reduce(21), // (, reduce: LexTerm
			nil,        // )
			reduce(21), // [, reduce: LexTerm
			nil,        // ]
			reduce(21), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S108
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(13), // regDefId, reduce: LexAlt
			nil,        // ignoredTokId
			reduce(13), // |, reduce: LexAlt
			reduce(13), // ., reduce: LexAlt
			reduce(13), // char_lit, reduce: LexAlt
			reduce(13), // ~, reduce: LexAlt
			nil,        // -
			reduce(13), // (, reduce: LexAlt
			nil,        // )
			reduce(13), // [, reduce: LexAlt
			nil,        // ]
			reduce(13), // {, reduce: LexAlt
			reduce(13), // }, reduce: LexAlt
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S109
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(131), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S110
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(16), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // ~, reduce: LexTerm
			nil,        // -
			reduce(16), // (, reduce: LexTerm
			nil,        // )
			reduce(16), // [, reduce: LexTerm
			nil,        // ]
			reduce(16), // {, reduce: LexTerm
			reduce(16), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S111
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(132), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S112
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(88),  // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			shift(133), // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S113
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(97),  // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			shift(134), // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S114
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			shift(106), // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			shift(135), // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S115
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(30), // ;, reduce: Alternatives
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(30), // |, reduce: Alternatives
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S116
		canRecover: true,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(35), // ;, reduce: SyntaxBody
			nil,        // regDefId
			nil,        // ignoredTokId
			reduce(35), // |, reduce: SyntaxBody
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S117
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(136), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S118
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			shift(49),  // regDefId
			nil,        // ignoredTokId
			reduce(11), // |, reduce: LexPattern
			shift(52),  // .
			shift(53),  // char_lit
			shift(54),  // ~
			nil,        // -
			shift(55),  // (
			reduce(11), // ), reduce: LexPattern
			shift(56),  // [
			nil,        // ]
			shift(57),  // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S119
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(17), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // ~, reduce: LexTerm
			nil,        // -
			reduce(17), // (, reduce: LexTerm
			reduce(17), // ), reduce: LexTerm
			reduce(17), // [, reduce: LexTerm
			nil,        // ]
			reduce(17), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S120
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			shift(137), // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S121
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(22), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(22), // |, reduce: LexTerm
			reduce(22), // ., reduce: LexTerm
			reduce(22), // char_lit, reduce: LexTerm
			reduce(22), // ~, reduce: LexTerm
			nil,        // -
			reduce(22), // (, reduce: LexTerm
			reduce(22), // ), reduce: LexTerm
			reduce(22), // [, reduce: LexTerm
			nil,        // ]
			reduce(22), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S122
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(20), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(20), // |, reduce: LexTerm
			reduce(20), // ., reduce: LexTerm
			reduce(20), // char_lit, reduce: LexTerm
			reduce(20), // ~, reduce: LexTerm
			nil,        // -
			reduce(20), // (, reduce: LexTerm
			reduce(20), // ), reduce: LexTerm
			reduce(20), // [, reduce: LexTerm
			nil,        // ]
			reduce(20), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S123
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(21), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(21), // |, reduce: LexTerm
			reduce(21), // ., reduce: LexTerm
			reduce(21), // char_lit, reduce: LexTerm
			reduce(21), // ~, reduce: LexTerm
			nil,        // -
			reduce(21), // (, reduce: LexTerm
			reduce(21), // ), reduce: LexTerm
			reduce(21), // [, reduce: LexTerm
			nil,        // ]
			reduce(21), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S124
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			shift(59),  // regDefId
			nil,        // ignoredTokId
			reduce(11), // |, reduce: LexPattern
			shift(62),  // .
			shift(63),  // char_lit
			shift(64),  // ~
			nil,        // -
			shift(65),  // (
			nil,        // )
			shift(66),  // [
			reduce(11), // ], reduce: LexPattern
			shift(67),  // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S125
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(17), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // ~, reduce: LexTerm
			nil,        // -
			reduce(17), // (, reduce: LexTerm
			nil,        // )
			reduce(17), // [, reduce: LexTerm
			reduce(17), // ], reduce: LexTerm
			reduce(17), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S126
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			shift(138), // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S127
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(22), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(22), // |, reduce: LexTerm
			reduce(22), // ., reduce: LexTerm
			reduce(22), // char_lit, reduce: LexTerm
			reduce(22), // ~, reduce: LexTerm
			nil,        // -
			reduce(22), // (, reduce: LexTerm
			nil,        // )
			reduce(22), // [, reduce: LexTerm
			reduce(22), // ], reduce: LexTerm
			reduce(22), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S128
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(20), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(20), // |, reduce: LexTerm
			reduce(20), // ., reduce: LexTerm
			reduce(20), // char_lit, reduce: LexTerm
			reduce(20), // ~, reduce: LexTerm
			nil,        // -
			reduce(20), // (, reduce: LexTerm
			nil,        // )
			reduce(20), // [, reduce: LexTerm
			reduce(20), // ], reduce: LexTerm
			reduce(20), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S129
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(21), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(21), // |, reduce: LexTerm
			reduce(21), // ., reduce: LexTerm
			reduce(21), // char_lit, reduce: LexTerm
			reduce(21), // ~, reduce: LexTerm
			nil,        // -
			reduce(21), // (, reduce: LexTerm
			nil,        // )
			reduce(21), // [, reduce: LexTerm
			reduce(21), // ], reduce: LexTerm
			reduce(21), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S130
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			shift(69),  // regDefId
			nil,        // ignoredTokId
			reduce(11), // |, reduce: LexPattern
			shift(72),  // .
			shift(73),  // char_lit
			shift(74),  // ~
			nil,        // -
			shift(75),  // (
			nil,        // )
			shift(76),  // [
			nil,        // ]
			shift(77),  // {
			reduce(11), // }, reduce: LexPattern
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S131
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(17), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // ~, reduce: LexTerm
			nil,        // -
			reduce(17), // (, reduce: LexTerm
			nil,        // )
			reduce(17), // [, reduce: LexTerm
			nil,        // ]
			reduce(17), // {, reduce: LexTerm
			reduce(17), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S132
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			shift(139), // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S133
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(22), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(22), // |, reduce: LexTerm
			reduce(22), // ., reduce: LexTerm
			reduce(22), // char_lit, reduce: LexTerm
			reduce(22), // ~, reduce: LexTerm
			nil,        // -
			reduce(22), // (, reduce: LexTerm
			nil,        // )
			reduce(22), // [, reduce: LexTerm
			nil,        // ]
			reduce(22), // {, reduce: LexTerm
			reduce(22), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S134
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(20), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(20), // |, reduce: LexTerm
			reduce(20), // ., reduce: LexTerm
			reduce(20), // char_lit, reduce: LexTerm
			reduce(20), // ~, reduce: LexTerm
			nil,        // -
			reduce(20), // (, reduce: LexTerm
			nil,        // )
			reduce(20), // [, reduce: LexTerm
			nil,        // ]
			reduce(20), // {, reduce: LexTerm
			reduce(20), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S135
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(21), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(21), // |, reduce: LexTerm
			reduce(21), // ., reduce: LexTerm
			reduce(21), // char_lit, reduce: LexTerm
			reduce(21), // ~, reduce: LexTerm
			nil,        // -
			reduce(21), // (, reduce: LexTerm
			nil,        // )
			reduce(21), // [, reduce: LexTerm
			nil,        // ]
			reduce(21), // {, reduce: LexTerm
			reduce(21), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S136
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			shift(140), // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S137
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(141), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S138
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(142), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S139
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			shift(143), // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			nil,        // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S140
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			reduce(18), // ;, reduce: LexTerm
			reduce(18), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(18), // |, reduce: LexTerm
			reduce(18), // ., reduce: LexTerm
			reduce(18), // char_lit, reduce: LexTerm
			reduce(18), // ~, reduce: LexTerm
			nil,        // -
			reduce(18), // (, reduce: LexTerm
			nil,        // )
			reduce(18), // [, reduce: LexTerm
			nil,        // ]
			reduce(18), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S141
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			shift(144), // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S142
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			shift(145), // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S143
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			nil,        // regDefId
			nil,        // ignoredTokId
			nil,        // |
			nil,        // .
			nil,        // char_lit
			nil,        // ~
			nil,        // -
			nil,        // (
			shift(146), // )
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S144
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(18), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(18), // |, reduce: LexTerm
			reduce(18), // ., reduce: LexTerm
			reduce(18), // char_lit, reduce: LexTerm
			reduce(18), // ~, reduce: LexTerm
			nil,        // -
			reduce(18), // (, reduce: LexTerm
			reduce(18), // ), reduce: LexTerm
			reduce(18), // [, reduce: LexTerm
			nil,        // ]
			reduce(18), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S145
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(18), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(18), // |, reduce: LexTerm
			reduce(18), // ., reduce: LexTerm
			reduce(18), // char_lit, reduce: LexTerm
			reduce(18), // ~, reduce: LexTerm
			nil,        // -
			reduce(18), // (, reduce: LexTerm
			nil,        // )
			reduce(18), // [, reduce: LexTerm
			reduce(18), // ], reduce: LexTerm
			reduce(18), // {, reduce: LexTerm
			nil,        // }
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
	actionRow{ // S146
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // tokId
			nil,        // :
			nil,        // ;
			reduce(18), // regDefId, reduce: LexTerm
			nil,        // ignoredTokId
			reduce(18), // |, reduce: LexTerm
			reduce(18), // ., reduce: LexTerm
			reduce(18), // char_lit, reduce: LexTerm
			reduce(18), // ~, reduce: LexTerm
			nil,        // -
			reduce(18), // (, reduce: LexTerm
			nil,        // )
			reduce(18), // [, reduce: LexTerm
			nil,        // ]
			reduce(18), // {, reduce: LexTerm
			reduce(18), // }, reduce: LexTerm
			nil,        // g_sdt_lit
			nil,        // prodId
			nil,        // error
			nil,        // empty
			nil,        // string_lit
		},
	},
}
