<< import "code.google.com/p/gocc/test/sr/ast" >>

Stmt :
		if id then Stmt					<< ast.NewIf($1, $3), nil >>
	|	if id then Stmt else Stmt		<< ast.NewIfElse($1, $3, $5), nil >>
	|	id								<< ast.NewIdStmt($0), nil >>
;

