<< import "code.google.com/p/gocc/example/astx/ast" >>

StmtList : 
      Stmt             << ast.NewStmtList($0) >>
    | StmtList Stmt    << ast.AppendStmt($0, $1) >>
;

Stmt : 
      id               << ast.NewStmt($0) >>
;