// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"fmt"
	"io/ioutil"
	"unicode/utf8"

	"github.com/maxcalandrelli/gocc/internal/frontend/reparsed/internal/util"
	"github.com/maxcalandrelli/gocc/internal/frontend/reparsed/internal/token"
)

const (
	NoState    = -1
	NumStates  = 109
	NumSymbols = 75
)

type Position struct {
	pos    int
	line   int
	column int
}

type Lexer struct {
  Position
	src    []byte
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{ src: src }
  lexer.Position.Reset()
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	fmt.Printf("Lexer.Scan() pos=%d\n", l.pos)
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		fmt.Printf("\tpos=%d, line=%d, col=%d, state=%d\n", l.pos, l.line, l.column, state)
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		fmt.Printf("\tS%d, : tok=%s, rune == %s(%x), next state == %d\n", state, token.TokMap.Id(tok.Type), util.RuneToString(rune1), rune1, nextState)
		fmt.Printf("\t\tpos=%d, size=%d, start=%d, end=%d\n", l.pos, size, start, end)
		if nextState != -1 {
			fmt.Printf("\t\taction:%s\n", ActTab[nextState].String())
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	fmt.Printf("Token at %s: %s \"%s\"\n", tok.String(), token.TokMap.Id(tok.Type), tok.Lit)

	return
}

func (l *Lexer) Reset() {
  l.Position.Reset()
}

func (l *Lexer) Reposition(p Position) {
  l.Position = p
}

func (l Lexer) CurrentPosition() Position {
  return l.Position
}

func (l Lexer) Source() []byte {
  return l.src
}

func (l Lexer) Remaining() []byte {
  return l.src[l.pos:]
}


func (p Position) Offset() int {
  return p.pos
}

func (p Position) Line() int {
  return p.line
}

func (p Position) Column() int {
  return p.column
}

func (p *Position) Reset()  {
	p.pos = 0
  p.line = 1
  p.column = 1
}

/*
Lexer symbols:
0: '_'
1: '!'
2: '''
3: '''
4: '<'
5: '<'
6: '>'
7: '>'
8: ':'
9: ';'
10: '|'
11: '.'
12: '-'
13: '~'
14: '('
15: ')'
16: '['
17: ']'
18: '{'
19: '}'
20: 'e'
21: 'r'
22: 'r'
23: 'o'
24: 'r'
25: \u03bb
26: 'e'
27: 'm'
28: 'p'
29: 't'
30: 'y'
31: \u03b5
32: '/'
33: '/'
34: '\n'
35: '/'
36: '*'
37: '*'
38: '*'
39: '/'
40: '_'
41: '\'
42: 'u'
43: '\'
44: 'U'
45: '\'
46: 'a'
47: 'b'
48: 'f'
49: 'n'
50: 'r'
51: 't'
52: 'v'
53: '\'
54: '''
55: '"'
56: '\'
57: '\'
58: 'x'
59: '`'
60: '`'
61: '"'
62: '"'
63: ' '
64: '\t'
65: '\n'
66: '\r'
67: 'a'-'z'
68: 'A'-'Z'
69: '0'-'9'
70: '0'-'7'
71: '0'-'9'
72: 'A'-'F'
73: 'a'-'f'
74: .
*/
