// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 39: // [''',''']
			return 4
		case r == 40: // ['(','(']
			return 5
		case r == 41: // [')',')']
			return 6
		case r == 45: // ['-','-']
			return 7
		case r == 46: // ['.','.']
			return 8
		case r == 47: // ['/','/']
			return 9
		case r == 58: // [':',':']
			return 10
		case r == 59: // [';',';']
			return 11
		case r == 60: // ['<','<']
			return 12
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case r == 91: // ['[','[']
			return 15
		case r == 93: // [']',']']
			return 16
		case r == 95: // ['_','_']
			return 17
		case r == 96: // ['`','`']
			return 18
		case 97 <= r && r <= 100: // ['a','d']
			return 19
		case r == 101: // ['e','e']
			return 20
		case 102 <= r && r <= 122: // ['f','z']
			return 19
		case r == 123: // ['{','{']
			return 21
		case r == 124: // ['|','|']
			return 22
		case r == 125: // ['}','}']
			return 23
		case r == 126: // ['~','~']
			return 24
		case r == 949: // [\u03b5,\u03b5]
			return 25
		case r == 955: // [\u03bb,\u03bb]
			return 26
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case 97 <= r && r <= 122: // ['a','z']
			return 27
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		case r == 92: // ['\','\']
			return 29
		default:
			return 30
		}
	},
	// S4
	func(r rune) int {
		switch {
		case r == 92: // ['\','\']
			return 31
		default:
			return 32
		}
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 33
		case r == 47: // ['/','/']
			return 34
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 60: // ['<','<']
			return 35
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 64: // ['@','@']
			return 36
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 37
		case 65 <= r && r <= 90: // ['A','Z']
			return 38
		case r == 95: // ['_','_']
			return 39
		case 97 <= r && r <= 122: // ['a','z']
			return 40
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 41
		case 65 <= r && r <= 90: // ['A','Z']
			return 42
		case r == 95: // ['_','_']
			return 43
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 96: // ['`','`']
			return 45
		default:
			return 18
		}
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 108: // ['a','l']
			return 49
		case r == 109: // ['m','m']
			return 50
		case 110 <= r && r <= 113: // ['n','q']
			return 49
		case r == 114: // ['r','r']
			return 51
		case 115 <= r && r <= 122: // ['s','z']
			return 49
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 54
		case 97 <= r && r <= 122: // ['a','z']
			return 55
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 56
		case r == 39: // [''',''']
			return 56
		case 48 <= r && r <= 55: // ['0','7']
			return 57
		case r == 85: // ['U','U']
			return 58
		case r == 92: // ['\','\']
			return 56
		case r == 97: // ['a','a']
			return 56
		case r == 98: // ['b','b']
			return 56
		case r == 102: // ['f','f']
			return 56
		case r == 110: // ['n','n']
			return 56
		case r == 114: // ['r','r']
			return 56
		case r == 116: // ['t','t']
			return 56
		case r == 117: // ['u','u']
			return 59
		case r == 118: // ['v','v']
			return 56
		case r == 120: // ['x','x']
			return 60
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		case r == 92: // ['\','\']
			return 29
		default:
			return 30
		}
	},
	// S31
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 61
		case r == 39: // [''',''']
			return 61
		case 48 <= r && r <= 55: // ['0','7']
			return 62
		case r == 85: // ['U','U']
			return 63
		case r == 92: // ['\','\']
			return 61
		case r == 97: // ['a','a']
			return 61
		case r == 98: // ['b','b']
			return 61
		case r == 102: // ['f','f']
			return 61
		case r == 110: // ['n','n']
			return 61
		case r == 114: // ['r','r']
			return 61
		case r == 116: // ['t','t']
			return 61
		case r == 117: // ['u','u']
			return 64
		case r == 118: // ['v','v']
			return 61
		case r == 120: // ['x','x']
			return 65
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 66
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 67
		default:
			return 33
		}
	},
	// S34
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 68
		default:
			return 34
		}
	},
	// S35
	func(r rune) int {
		switch {
		default:
			return 69
		}
	},
	// S36
	func(r rune) int {
		switch {
		default:
			return 70
		}
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 37
		case 65 <= r && r <= 90: // ['A','Z']
			return 38
		case r == 95: // ['_','_']
			return 39
		case 97 <= r && r <= 122: // ['a','z']
			return 40
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 37
		case 65 <= r && r <= 90: // ['A','Z']
			return 38
		case r == 95: // ['_','_']
			return 39
		case 97 <= r && r <= 122: // ['a','z']
			return 40
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 37
		case 65 <= r && r <= 90: // ['A','Z']
			return 38
		case r == 95: // ['_','_']
			return 39
		case 97 <= r && r <= 122: // ['a','z']
			return 40
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 37
		case 65 <= r && r <= 90: // ['A','Z']
			return 38
		case r == 95: // ['_','_']
			return 39
		case 97 <= r && r <= 122: // ['a','z']
			return 40
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 41
		case 65 <= r && r <= 90: // ['A','Z']
			return 42
		case r == 95: // ['_','_']
			return 43
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 41
		case 65 <= r && r <= 90: // ['A','Z']
			return 42
		case r == 95: // ['_','_']
			return 43
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 41
		case 65 <= r && r <= 90: // ['A','Z']
			return 42
		case r == 95: // ['_','_']
			return 43
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 41
		case 65 <= r && r <= 90: // ['A','Z']
			return 42
		case r == 95: // ['_','_']
			return 43
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 111: // ['a','o']
			return 49
		case r == 112: // ['p','p']
			return 71
		case 113 <= r && r <= 122: // ['q','z']
			return 49
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 113: // ['a','q']
			return 49
		case r == 114: // ['r','r']
			return 72
		case 115 <= r && r <= 122: // ['s','z']
			return 49
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 54
		case 97 <= r && r <= 122: // ['a','z']
			return 55
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 54
		case 97 <= r && r <= 122: // ['a','z']
			return 55
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 54
		case 97 <= r && r <= 122: // ['a','z']
			return 55
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 54
		case 97 <= r && r <= 122: // ['a','z']
			return 55
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		case r == 92: // ['\','\']
			return 29
		default:
			return 30
		}
	},
	// S57
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 73
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 74
		case 65 <= r && r <= 70: // ['A','F']
			return 74
		case 97 <= r && r <= 102: // ['a','f']
			return 74
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 75
		case 65 <= r && r <= 70: // ['A','F']
			return 75
		case 97 <= r && r <= 102: // ['a','f']
			return 75
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case 65 <= r && r <= 70: // ['A','F']
			return 76
		case 97 <= r && r <= 102: // ['a','f']
			return 76
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 66
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 77
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 78
		case 65 <= r && r <= 70: // ['A','F']
			return 78
		case 97 <= r && r <= 102: // ['a','f']
			return 78
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case 65 <= r && r <= 70: // ['A','F']
			return 79
		case 97 <= r && r <= 102: // ['a','f']
			return 79
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 80
		case 65 <= r && r <= 70: // ['A','F']
			return 80
		case 97 <= r && r <= 102: // ['a','f']
			return 80
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 67
		case r == 47: // ['/','/']
			return 81
		default:
			return 33
		}
	},
	// S68
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 82
		default:
			return 69
		}
	},
	// S70
	func(r rune) int {
		switch {
		case r == 64: // ['@','@']
			return 83
		default:
			return 70
		}
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 115: // ['a','s']
			return 49
		case r == 116: // ['t','t']
			return 84
		case 117 <= r && r <= 122: // ['u','z']
			return 49
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 110: // ['a','n']
			return 49
		case r == 111: // ['o','o']
			return 85
		case 112 <= r && r <= 122: // ['p','z']
			return 49
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 86
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 87
		case 65 <= r && r <= 70: // ['A','F']
			return 87
		case 97 <= r && r <= 102: // ['a','f']
			return 87
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 88
		case 65 <= r && r <= 70: // ['A','F']
			return 88
		case 97 <= r && r <= 102: // ['a','f']
			return 88
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 89
		case 65 <= r && r <= 70: // ['A','F']
			return 89
		case 97 <= r && r <= 102: // ['a','f']
			return 89
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 90
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 91
		case 65 <= r && r <= 70: // ['A','F']
			return 91
		case 97 <= r && r <= 102: // ['a','f']
			return 91
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 92
		case 65 <= r && r <= 70: // ['A','F']
			return 92
		case 97 <= r && r <= 102: // ['a','f']
			return 92
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 93
		case 65 <= r && r <= 70: // ['A','F']
			return 93
		case 97 <= r && r <= 102: // ['a','f']
			return 93
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 94
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case r == 64: // ['@','@']
			return 95
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 120: // ['a','x']
			return 49
		case r == 121: // ['y','y']
			return 96
		case r == 122: // ['z','z']
			return 49
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 113: // ['a','q']
			return 49
		case r == 114: // ['r','r']
			return 97
		case 115 <= r && r <= 122: // ['s','z']
			return 49
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		case r == 92: // ['\','\']
			return 29
		default:
			return 30
		}
	},
	// S87
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 98
		case 65 <= r && r <= 70: // ['A','F']
			return 98
		case 97 <= r && r <= 102: // ['a','f']
			return 98
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 99
		case 65 <= r && r <= 70: // ['A','F']
			return 99
		case 97 <= r && r <= 102: // ['a','f']
			return 99
		}
		return NoState
	},
	// S89
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		case r == 92: // ['\','\']
			return 29
		default:
			return 30
		}
	},
	// S90
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 66
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 100
		case 65 <= r && r <= 70: // ['A','F']
			return 100
		case 97 <= r && r <= 102: // ['a','f']
			return 100
		}
		return NoState
	},
	// S92
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 101
		case 65 <= r && r <= 70: // ['A','F']
			return 101
		case 97 <= r && r <= 102: // ['a','f']
			return 101
		}
		return NoState
	},
	// S93
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 66
		}
		return NoState
	},
	// S94
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S95
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S96
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S97
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case 65 <= r && r <= 90: // ['A','Z']
			return 47
		case r == 95: // ['_','_']
			return 48
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S98
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 102
		case 65 <= r && r <= 70: // ['A','F']
			return 102
		case 97 <= r && r <= 102: // ['a','f']
			return 102
		}
		return NoState
	},
	// S99
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 103
		case 65 <= r && r <= 70: // ['A','F']
			return 103
		case 97 <= r && r <= 102: // ['a','f']
			return 103
		}
		return NoState
	},
	// S100
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 104
		case 65 <= r && r <= 70: // ['A','F']
			return 104
		case 97 <= r && r <= 102: // ['a','f']
			return 104
		}
		return NoState
	},
	// S101
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 105
		case 65 <= r && r <= 70: // ['A','F']
			return 105
		case 97 <= r && r <= 102: // ['a','f']
			return 105
		}
		return NoState
	},
	// S102
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 106
		case 65 <= r && r <= 70: // ['A','F']
			return 106
		case 97 <= r && r <= 102: // ['a','f']
			return 106
		}
		return NoState
	},
	// S103
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		case r == 92: // ['\','\']
			return 29
		default:
			return 30
		}
	},
	// S104
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 107
		case 65 <= r && r <= 70: // ['A','F']
			return 107
		case 97 <= r && r <= 102: // ['a','f']
			return 107
		}
		return NoState
	},
	// S105
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 66
		}
		return NoState
	},
	// S106
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 108
		case 65 <= r && r <= 70: // ['A','F']
			return 108
		case 97 <= r && r <= 102: // ['a','f']
			return 108
		}
		return NoState
	},
	// S107
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 109
		case 65 <= r && r <= 70: // ['A','F']
			return 109
		case 97 <= r && r <= 102: // ['a','f']
			return 109
		}
		return NoState
	},
	// S108
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 110
		case 65 <= r && r <= 70: // ['A','F']
			return 110
		case 97 <= r && r <= 102: // ['a','f']
			return 110
		}
		return NoState
	},
	// S109
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 111
		case 65 <= r && r <= 70: // ['A','F']
			return 111
		case 97 <= r && r <= 102: // ['a','f']
			return 111
		}
		return NoState
	},
	// S110
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 112
		case 65 <= r && r <= 70: // ['A','F']
			return 112
		case 97 <= r && r <= 102: // ['a','f']
			return 112
		}
		return NoState
	},
	// S111
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 113
		case 65 <= r && r <= 70: // ['A','F']
			return 113
		case 97 <= r && r <= 102: // ['a','f']
			return 113
		}
		return NoState
	},
	// S112
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		case r == 92: // ['\','\']
			return 29
		default:
			return 30
		}
	},
	// S113
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 66
		}
		return NoState
	},
}
