// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // Π<S'>
		1, // Π<Calc>
		2, // Π<Expr>
		3, // Π<Term>
		4, // Π<Factor>
	},
	gotoRow{ // S1
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S2
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S3
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S4
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S5
		-1, // Π<S'>
		-1, // Π<Calc>
		9, // Π<Expr>
		10, // Π<Term>
		11, // Π<Factor>
	},
	gotoRow{ // S6
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S7
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		14, // Π<Term>
		4, // Π<Factor>
	},
	gotoRow{ // S8
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		15, // Π<Factor>
	},
	gotoRow{ // S9
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S10
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S11
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S12
		-1, // Π<S'>
		-1, // Π<Calc>
		19, // Π<Expr>
		10, // Π<Term>
		11, // Π<Factor>
	},
	gotoRow{ // S13
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S14
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S15
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S16
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		20, // Π<Term>
		11, // Π<Factor>
	},
	gotoRow{ // S17
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S18
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		21, // Π<Factor>
	},
	gotoRow{ // S19
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S20
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S21
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S22
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
}
