// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // Π<S'>
		1, // Π<Calc>
		2, // Π<Expr>
		3, // Π<Term>
		4, // Π<Factor>
	},
	gotoRow{ // S1
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S2
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S3
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S4
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S5
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		12, // Π<Term>
		13, // Π<Factor>
	},
	gotoRow{ // S6
		-1, // Π<S'>
		-1, // Π<Calc>
		16, // Π<Expr>
		17, // Π<Term>
		18, // Π<Factor>
	},
	gotoRow{ // S7
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S8
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		22, // Π<Term>
		13, // Π<Factor>
	},
	gotoRow{ // S9
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		23, // Π<Term>
		13, // Π<Factor>
	},
	gotoRow{ // S10
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		24, // Π<Factor>
	},
	gotoRow{ // S11
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		25, // Π<Factor>
	},
	gotoRow{ // S12
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S13
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S14
		-1, // Π<S'>
		-1, // Π<Calc>
		29, // Π<Expr>
		17, // Π<Term>
		18, // Π<Factor>
	},
	gotoRow{ // S15
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S16
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S17
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S18
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S19
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		35, // Π<Term>
		36, // Π<Factor>
	},
	gotoRow{ // S20
		-1, // Π<S'>
		-1, // Π<Calc>
		39, // Π<Expr>
		17, // Π<Term>
		18, // Π<Factor>
	},
	gotoRow{ // S21
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S22
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S23
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S24
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S25
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S26
		-1, // Π<S'>
		-1, // Π<Calc>
		40, // Π<Expr>
		17, // Π<Term>
		18, // Π<Factor>
	},
	gotoRow{ // S27
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S28
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		41, // Π<Factor>
	},
	gotoRow{ // S29
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S30
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S31
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		43, // Π<Term>
		36, // Π<Factor>
	},
	gotoRow{ // S32
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		44, // Π<Term>
		36, // Π<Factor>
	},
	gotoRow{ // S33
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		45, // Π<Factor>
	},
	gotoRow{ // S34
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		46, // Π<Factor>
	},
	gotoRow{ // S35
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S36
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S37
		-1, // Π<S'>
		-1, // Π<Calc>
		50, // Π<Expr>
		17, // Π<Term>
		18, // Π<Factor>
	},
	gotoRow{ // S38
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S39
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S40
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S41
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S42
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S43
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S44
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S45
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S46
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S47
		-1, // Π<S'>
		-1, // Π<Calc>
		53, // Π<Expr>
		17, // Π<Term>
		18, // Π<Factor>
	},
	gotoRow{ // S48
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S49
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		54, // Π<Factor>
	},
	gotoRow{ // S50
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S51
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S52
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S53
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S54
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S55
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
	gotoRow{ // S56
		-1, // Π<S'>
		-1, // Π<Calc>
		-1, // Π<Expr>
		-1, // Π<Term>
		-1, // Π<Factor>
	},
}
