// Code generated by gocc; DO NOT EDIT.

package sr

import (
	"github.com/maxcalandrelli/gocc/example/sr/sr.grammar/sr/internal/util"
)

type EscapedString = util.EscapedString

func RuneToString(r rune) string {
	return util.RuneToString(r)
}

func HexDigitValue(ch rune) int {
	return util.HexDigitValue(ch)
}

func IntValue(lit []byte) (int64, error) {
	return util.IntValue(lit)
}

func UintValue(lit []byte) (uint64, error) {
	return util.UintValue(lit)
}
