// Code generated by gocc; DO NOT EDIT.

package fe2

import (
	"io"

	"github.com/maxcalandrelli/gocc/internal/fe2/internal/io/stream"
	"github.com/maxcalandrelli/gocc/internal/fe2/internal/lexer"
	"github.com/maxcalandrelli/gocc/internal/fe2/internal/parser"
	"github.com/maxcalandrelli/gocc/internal/fe2/internal/token"
)

type Token = token.Token
type WindowReader = stream.WindowReader

func ParseFile(fpath string) (interface{}, error) {
	if lexer, err := NewLexerFile(fpath); err == nil {
		return NewParser().Parse(lexer)
	} else {
		return nil, err
	}
}

func ParseText(text string) (interface{}, error) {
	return NewParser().Parse(NewLexer([]byte(text)))
}

func NewLexer(src []byte) *lexer.Lexer {
	return lexer.NewLexer(src)
}

func NewLexerFile(fpath string) (*lexer.Lexer, error) {
	return lexer.NewLexerFile(fpath)
}

func NewParser() *parser.Parser {
	return parser.NewParser()
}

func NewWindowReaderFromBytes(src []byte) WindowReader {
	return stream.NewWindowReaderFromBytes(src)
}

func NewWindowReader(rdr io.Reader) WindowReader {
	return stream.NewWindowReader(rdr)
}

func NewLimitedWindowReader(rdr io.Reader, sizeMin, sizeMax int) WindowReader {
	return stream.NewLimitedWindowReader(rdr, sizeMin, sizeMax)
}
