!comment      : _lineComment | _blockComment ;
!whitespace : ' ' | '\t' | '\n' | '\r' ;

_lineComment : '/' '/' {.} '\n' ;
_blockComment : '/' '*' {. | '*'} '*' '/' ;
_tokId : _lowcase {_id_char} ;
_lowcase : 'a'-'z' ;
_id_char : _upcase | _lowcase | '_' | _digit ;
_upcase : 'A'-'Z' ;
_digit : '0'-'9' ;


!space    :  ' ' | '\t' ;
hexdigit : '0'-'F'  | ~(':'-'@') ;

<<
import(
	"fmt"
)
>>

Test :
		Test1
;

Test1:
 "try" Test2
;

Test2 : Test3 | Test1;

Test3 :
"not" "empty"
|
T
|
hexdigit
;

T : "a"  | "X" | ProdX | "λ1" | X;

ProdX : "empty" | "ε" | "λ" | empty  | ε ;

X:
		"!"
	| 	"hexdigit"
	|
		altro
		@< altro() >@
			<<
				fmt.Printf("$0=%q\n$1=%q\n", $0, $1)
			>>
;

