
!space    :  ' ' | '\t' ;

hexdigit : '0'-'F'  | ~(':'-'@') ;

Test :
		Test1
;

Test1:
 "try" Test2
;

Test2 : Test3 | Test1;

Test3 :
"not" "empty"
|
T
|
hexdigit
;

T : "a"  | "X" | ProdX | "λ1";

ProdX : "empty" | "ε" | "λ" | empty  | ε ;

X: "!" | "hexdigit";

