// Code generated by gocc; DO NOT EDIT.

package reparsed

import (
	"io"

	"github.com/maxcalandrelli/gocc/internal/frontend/reparsed/internal/io/stream"
	"github.com/maxcalandrelli/gocc/internal/frontend/reparsed/internal/lexer"
	"github.com/maxcalandrelli/gocc/internal/frontend/reparsed/internal/parser"
	"github.com/maxcalandrelli/gocc/internal/frontend/reparsed/internal/token"
)

type (
	Token        = token.Token
	TokenStream  = token.TokenStream
	WindowReader = stream.WindowReader
	Scanner      = parser.Scanner
)

func ParseFile(fpath string) (interface{}, error) {
	if lexer, err := NewLexerFile(fpath); err == nil {
		return NewParser().Parse(lexer)
	} else {
		return nil, err
	}
}

func ParseText(text string) (interface{}, error) {
	return NewParser().Parse(NewLexerBytes([]byte(text)))
}

func NewLexerBytes(src []byte) *lexer.Lexer {
	return lexer.NewLexerBytes(src)
}

func NewLexerFile(fpath string) (*lexer.Lexer, error) {
	return lexer.NewLexerFile(fpath)
}

func NewParser() *parser.Parser {
	return parser.NewParser()
}

func NewWindowReaderFromBytes(src []byte) WindowReader {
	return stream.NewWindowReaderFromBytes(src)
}

func NewWindowReader(rdr io.Reader) WindowReader {
	return stream.NewWindowReader(rdr)
}

func NewLimitedWindowReader(rdr io.Reader, sizeMin, sizeMax int) WindowReader {
	return stream.NewLimitedWindowReader(rdr, sizeMin, sizeMax)
}
