// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	cdFunc      func(TokenStream, interface{}) (interface{}, error, []byte)
	cdAction    struct {
		tokenIndex   int
		tokenScanner cdFunc
	}
	actionRow struct {
		canRecover bool
		actions    [numSymbols]action
		cdActions  []cdAction
	}
	actions struct {
		table actionTable
	}
)

var parserActions = actions{
	table: actionTable{
		actionRow{ // S0
			canRecover: false,
			actions: [numSymbols]action{
				nil,      // ά<INVALID>
				nil,      // Ω<EOF>
				shift(3), // id
				shift(4), // μ<calc_0>
			},
			cdActions: []cdAction{
				cdAction{tokenIndex: 3, tokenScanner: cdFunc_calc_0},
			},
		},
		actionRow{ // S1
			canRecover: false,
			actions: [numSymbols]action{
				nil,          // ά<INVALID>
				accept(true), // Ω<EOF>
				shift(3),     // id
				shift(4),     // μ<calc_0>
			},
			cdActions: []cdAction{
				cdAction{tokenIndex: 3, tokenScanner: cdFunc_calc_0},
			},
		},
		actionRow{ // S2
			canRecover: false,
			actions: [numSymbols]action{
				nil,       // ά<INVALID>
				reduce(1), // Ω<EOF>, reduce: StmtList
				reduce(1), // id, reduce: StmtList
				reduce(1), // μ<calc_0>, reduce: StmtList
			},
			cdActions: []cdAction{
				cdAction{tokenIndex: 3, tokenScanner: cdFunc_calc_0},
			},
		},
		actionRow{ // S3
			canRecover: false,
			actions: [numSymbols]action{
				nil,       // ά<INVALID>
				reduce(3), // Ω<EOF>, reduce: Stmt
				reduce(3), // id, reduce: Stmt
				reduce(3), // μ<calc_0>, reduce: Stmt
			},
			cdActions: []cdAction{
				cdAction{tokenIndex: 3, tokenScanner: cdFunc_calc_0},
			},
		},
		actionRow{ // S4
			canRecover: false,
			actions: [numSymbols]action{
				nil,       // ά<INVALID>
				reduce(4), // Ω<EOF>, reduce: Stmt
				reduce(4), // id, reduce: Stmt
				reduce(4), // μ<calc_0>, reduce: Stmt
			},
			cdActions: []cdAction{
				cdAction{tokenIndex: 3, tokenScanner: cdFunc_calc_0},
			},
		},
		actionRow{ // S5
			canRecover: false,
			actions: [numSymbols]action{
				nil,       // ά<INVALID>
				reduce(2), // Ω<EOF>, reduce: StmtList
				reduce(2), // id, reduce: StmtList
				reduce(2), // μ<calc_0>, reduce: StmtList
			},
			cdActions: []cdAction{
				cdAction{tokenIndex: 3, tokenScanner: cdFunc_calc_0},
			},
		},
	},
}
