// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 1
		case 48 <= r && r <= 57: // ['0','9']
			return 2
		case r == 58: // [':',':']
			return 3
		case r == 59: // [';',';']
			return 4
		case r == 61: // ['=','=']
			return 5
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 117: // ['a','u']
			return 6
		case r == 118: // ['v','v']
			return 8
		case 119 <= r && r <= 122: // ['w','z']
			return 6
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 9
		case 48 <= r && r <= 57: // ['0','9']
			return 2
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 10
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 6
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 6
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 6
		case r == 97: // ['a','a']
			return 11
		case 98 <= r && r <= 122: // ['b','z']
			return 6
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 12
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 6
		case 97 <= r && r <= 113: // ['a','q']
			return 6
		case r == 114: // ['r','r']
			return 13
		case 115 <= r && r <= 122: // ['s','z']
			return 6
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 12
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 6
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		}
		return NoState
	},
}
