// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // Π<S'>
		1, // Π<RR>
		2, // Π<A>
		3, // Π<B>
	},
	gotoRow{ // S1
		-1, // Π<S'>
		-1, // Π<RR>
		-1, // Π<A>
		-1, // Π<B>
	},
	gotoRow{ // S2
		-1, // Π<S'>
		-1, // Π<RR>
		-1, // Π<A>
		-1, // Π<B>
	},
	gotoRow{ // S3
		-1, // Π<S'>
		-1, // Π<RR>
		-1, // Π<A>
		-1, // Π<B>
	},
	gotoRow{ // S4
		-1, // Π<S'>
		-1, // Π<RR>
		-1, // Π<A>
		-1, // Π<B>
	},
	gotoRow{ // S5
		-1, // Π<S'>
		-1, // Π<RR>
		-1, // Π<A>
		-1, // Π<B>
	},
	gotoRow{ // S6
		-1, // Π<S'>
		-1, // Π<RR>
		-1, // Π<A>
		-1, // Π<B>
	},
}
