// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Declaration
		3,  // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Declaration
		-1, // Name
		6,  // Equal
		-1, // Default
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		10, // Default
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Declaration
		-1, // Name
		-1, // Equal
		-1, // Default
	},
}
