// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // Π<S'>
		1, // Π<StmtList>
		2, // Π<Stmt_s>
		3, // Π<Stmt>
		4, // Π<StmtPref>
	},
	gotoRow{ // S1
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S2
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S3
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S4
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S5
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S6
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S7
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		9, // Π<Stmt>
		4, // Π<StmtPref>
	},
	gotoRow{ // S8
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S9
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S10
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
	gotoRow{ // S11
		-1, // Π<S'>
		-1, // Π<StmtList>
		-1, // Π<Stmt_s>
		-1, // Π<Stmt>
		-1, // Π<StmtPref>
	},
}
