// Code generated by gocc; DO NOT EDIT.

package nolexer

import (
	"github.com/maxcalandrelli/gocc/example/nolexer/nolexer.grammar/nolexer/internal/errors"
	"github.com/maxcalandrelli/gocc/example/nolexer/nolexer.grammar/nolexer/internal/parser"
	"github.com/maxcalandrelli/gocc/example/nolexer/nolexer.grammar/nolexer/internal/token"
)

const (
	INVALID = token.INVALID
	EOF     = token.EOF
)

type (
	Token       = token.Token
	TokenMap    = token.TokenMap
	Pos         = token.Pos
	ErrorSymbol = errors.ErrorSymbol
	Error       = errors.Error
	Parser      = parser.Parser
)

func NewParser() *parser.Parser {
	return parser.NewParser()
}

func GetTokenMap() TokenMap {
	return token.TokMap
}
